# Generated by Django 3.2.8 on 2021-11-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of a vehicle', max_length=50)),
                ('speed', models.DecimalField(decimal_places=2, help_text='Enter the speed of the vehicle (in Kmph)', max_digits=4)),
                ('average_speed', models.DecimalField(decimal_places=2, help_text='Enter the average speed of the vehicle (in Kmph)', max_digits=4)),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Enter the temperature of the vehicle (in celcius)', max_digits=3)),
                ('fuel_level', models.IntegerField(verbose_name='Enter the fuel level of the vehicle (in percentage)')),
                ('engine_status', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], help_text='Choose the engine status', max_length=3)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
