# Generated by Django 3.2.8 on 2021-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='average_speed',
            field=models.FloatField(help_text='Enter the average speed of the vehicle (in kmph)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.FloatField(help_text='Enter the speed of the vehicle (in kmph)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='temperature',
            field=models.FloatField(help_text='Enter the temperature of the vehicle (in celcius)'),
        ),
    ]
